[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "rpi-sentry-sandbox"
version = "0.1.0"
description = "Sandbox for RPI Sentry"
authors = ["mstream <maciej.laciak@gmail.com>"]

[tool.poetry.scripts]
sandbox = 'rpi_sentry_sandbox:main'
