---
- hosts: all
  remote_user: pi
  become: true
  vars:
    ansible_python_interpreter: python3
    boot_config:
      arm_64bit: '1'
      arm_boost: '1'
      camera_auto_detect: '1'
      display_auto_detect: '0'
      disable_fw_kms_setup: '1'
      disable_overscan: '1'
      max_framebuffers: '2'
      # arm_freq: '600'
      # arm_freq_min: '600'
      # over_voltage: '-8'
      # over_voltage_min: '-8'
    boot_config_lines:
      - dtoverlay=disable-bt
      - dtoverlay=vc4-kms-v3d,cma-320
      - dtparam=audio=off
    cmdline: console=serial0,115200 console=tty1 rootfstype=ext4 fsck.repair=yes
      rootwait cfg80211.ieee80211_regdom=GB
    arducam_enabled: '{{ arducam | default(false) | bool }}'
    swap_file_path: /var/swap
    zram_log:
      alg: zstd
      mem_limit: 32M
      disk_size: 96M
    zram_swap:
      alg: zstd
      mem_limit: 128M
      disk_size: 256M
  environment:
    GIT_SSL_NO_VERIFY: 'true'
  handlers:
    - name: reboot
      ansible.builtin.reboot:
        reboot_timeout: 300
  pre_tasks:
    - name: Copy over authorized SSH public key
      ansible.posix.authorized_key:
        user: '{{ ansible_user }}'
        state: present
        key: '{{ lookup("file", lookup("env","HOME") + "/.ssh/id_rsa.pub") }}'
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
    - name: Install playbook dependencies
      ansible.builtin.apt:
        name: '{{ item }}'
        state: latest
        install_recommends: false
        update_cache: false
      loop: [git, openssh-server, python3]
  tasks:
    - name: Set up services
      ansible.builtin.include_tasks:
        file: tasks/services.yml
    - name: Tweak boot configuration
      ansible.builtin.include_tasks:
        file: tasks/{{ item }}
      loop: [rpi-boot-config.yml, rpi-cmdline.yml]
    - name: Set up swap file
      ansible.builtin.include_role:
        name: swap
    - name: Set up ZRAM swap partition
      ansible.builtin.include_role:
        name: zram
    - name: Update system settings
      ansible.posix.sysctl:
        name: '{{ item.name }}'
        value: '{{ item.value }}'
        state: present
      loop:
        - name: vm.dirty_ratio
          value: '50'
        - name: vm.dirty_background_ratio
          value: '1'
        - name: vm.swappiness
          value: '100'
        - name: vm.vfs_cache_pressure
          value: '500'
    - name: Set up python
      ansible.builtin.include_tasks:
        file: tasks/python.yml
    - name: Set up Arducam camera
      tags: [arducam]
      ansible.builtin.include_tasks:
        file: tasks/arducam.yml
      when: arducam_enabled
    - name: Set up RPI Sentry
      tags: [rpi-sentry]
      ansible.builtin.include_tasks:
        file: tasks/rpi-sentry.yml
