---
- name: Check if zram-config is installed
  shell: ls /etc/systemd/system | grep zram-config.service
  register: zram_installed_result
  changed_when: false
  failed_when: false
- ansible.builtin.include_tasks: zram-uninstall.yml
  when: zram_installed_result.rc == 0 and zram_upgrade
- ansible.builtin.include_tasks: zram-install.yml
  when: zram_installed_result.rc == 1 or (zram_installed_result.rc == 0 and zram_upgrade)
- ansible.builtin.include_tasks: zram-config.yml
