[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "rpi-sentry-core"
version = "0.1.0"
description = "Core logic for RPI Sentry"
authors = ["mstream <maciej.laciak@gmail.com>"]
