---
- name: Install Python libraries
  ansible.builtin.apt:
    name: python3-{{ item }}
    state: latest
    install_recommends: false
    update_cache: false
  loop: [aiohttp, aiohttp-jinja2, avro, opencv, picamera2]
