---
- name: RPI Sentry tasks
  tags: [rpi-sentry]
  block:
    - name: Install Health Check dependencies
      ansible.builtin.apt:
        name: httping
        state: latest
        install_recommends: false
        update_cache: false
    - name: RPI Sentry | Create deployment directories
      ansible.builtin.file:
        path: /opt/{{ item }}
        state: directory
        owner: pi
        group: pi
      loop: [rpi-sentry, rpi-sentry-health-check]
    - name: RPI Sentry | Create config directory
      ansible.builtin.file:
        path: /etc/rpi-sentry
        state: directory
        owner: root
        group: root
    - name: RPI Sentry | Create environment file
      ansible.builtin.template:
        dest: /etc/rpi-sentry/rpi-sentry.env
        group: root
        src: rpi-sentry.env.j2
        mode: 0644
        owner: root
    - name: RPI Sentry | Create service unit files
      ansible.builtin.template:
        dest: /etc/systemd/system/{{ item }}.service
        group: root
        src: '{{ item }}.service.j2'
        mode: 0644
        owner: root
      loop: [rpi-sentry, rpi-sentry-health-check]
    - name: RPI Sentry | Create timer unit files
      ansible.builtin.template:
        dest: /etc/systemd/system/{{ item }}.timer
        group: root
        src: '{{ item }}.timer.j2'
        mode: 0644
        owner: root
      loop: [rpi-sentry-health-check]
    - name: RPI Sentry | Enable and start service
      ansible.builtin.systemd_service:
        name: rpi-sentry
        daemon_reload: true
        enabled: true
        masked: false
        state: started
      loop: [rpi-sentry.service, rpi-sentry-health-check.timer]
