---
- hosts: all
  become: true
  roles: [zram]
  vars:
    ansible_python_interpreter: python3
    zram_log:
      alg: zstd
      mem_limit: 32M
      disk_size: 96M
    zram_swap:
      alg: zstd
      mem_limit: 128M
      disk_size: 256M
  tasks:
    - name: Install Picamera2
      ansible.builtin.apt:
        name: python3-picamera2
        state: present
        install_recommends: false
    - name: Install gpiozero
      ansible.builtin.apt:
        name: python3-gpiozero
        state: present
        install_recommends: false
    - name: Install pydantic
      ansible.builtin.apt:
        name: python3-pydantic
        state: present
        install_recommends: false
    - name: Install RPI.GPIO
      ansible.builtin.apt:
        name: python3-rpi.gpio
        state: present
        install_recommends: false
