---
- hosts: all
  become: true
  roles: [zram]
  vars:
    ansible_python_interpreter: python3
    zram_log:
      alg: zstd
      mem_limit: 32M
      disk_size: 96M
    zram_swap:
      alg: zstd
      mem_limit: 128M
      disk_size: 256M
  tasks:
    - name: Install Python libraries
      ansible.builtin.apt:
        name: python3-{{ item }}
        state: present
        install_recommends: false
      loop:
        - aiohttp
        - aiohttp-jinja2
        - avro
        - gpiozero
        - opencv
        - picamera2
        - rpi.gpio
